# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29c9d884405a83136158869c11208abbdcc8093316581c922a2a01cc36afd3a7773ad16f630f62f8f465ad3458e00c599cf1f8b01502926aa09b0a60e61e5d4d

test:
  secret_key_base: d2461c0cc8bc926e58fa8fe76647ae564a8b1030f0bf8cf1c9e9460b5733ba8a110bbccb03a32f7adad9bed34d3c60361d1c14a430b358d5f5c6bd8f43fb63f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
